name: Magi build (Ubuntu Static i386)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: debian:stable-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get install aptitude -y
          #apt-get upgrade
          aptitude install crossbuild-essential-i386 libssl-dev:i386 libgmp-dev:i386 libminiupnpc-dev:i386 libboost-all-dev:i386 libprotobuf-dev:i386 libqrencode-dev:i386 -y

      - name: Build Berkeley DB
        run: |
          cd src/db-4.8.30.NC/build_unix && ../dist/configure --enable-cxx --disable-shared --with-pic --target=i386-linux-gnu CC=i686-linux-gnu-gcc CXX=i686-linux-gnu-g++
          # CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32
          cd src/db-4.8.30.NC/build_unix && make

      - name: Compile Magi
        run: |
          cd src && make -f makefile.unix -j6 CXX="i686-linux-gnu-g++" STATIC=1 LDFLAGS="-static-libstdc++ -static-libgcc" 
          # CXXFLAGS="-m32"
          ls
          strip magid

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: magid-dev
          path: ./src/magid
